`timescale 1ns/1ps
`default_nettype none
// Development self-test only: provisions PUBLIC TEST KEY d=1, never a real key.
// Executes the same register transactions in simulation and on the board.
module tinysign_board_selftest #(parameter integer WATCHDOG_CYCLES=8000000) (
    input wire clk, input wire rst_n,
    output reg finished, output reg passed, output reg [7:0] failure_code,
    output reg [31:0] provision_cycles, output reg [31:0] sign_cycles,
    output wire core_busy, output wire [7:0] step
);
    localparam [2:0] OP_WRITE=0, OP_CHECK=1, OP_WAIT=2, OP_DELAY=3, OP_END=4;
    localparam [1:0] ST_FETCH=0, ST_EXECUTE=1, ST_SETTLE=2;
    reg [1:0] state;
    reg [7:0] pc;
    reg [2:0] operation;
    reg [7:0] address;
    reg [31:0] expected, mask, wait_cycles;
    reg bus_write;
    reg [7:0] bus_address;
    reg [31:0] bus_write_data;
    wire [31:0] bus_read_data;
    reg [1:0] timing_kind;
    reg [31:0] operation_cycles;
    reg captured_sign;
    assign step=pc;
    tinysign_core u_core(.clk(clk),.rst_n(rst_n),.bus_write(bus_write),
        .bus_address(bus_address),.bus_write_data(bus_write_data),
        .bus_byte_enable(4'hf),.bus_read_data(bus_read_data),.busy(core_busy));

    // Public vectors: d=1, SHA-256("sample"), independently generated by p256.py.
    always @* begin
        operation=OP_END; address=0; expected=0; mask=0;
        case(pc)
            8'd0: begin operation=OP_WRITE; address=8'h10; expected=32'h00000000; mask=32'hffffffff; end
            8'd1: begin operation=OP_WRITE; address=8'h14; expected=32'h00000000; mask=32'hffffffff; end
            8'd2: begin operation=OP_WRITE; address=8'h18; expected=32'h00000000; mask=32'hffffffff; end
            8'd3: begin operation=OP_WRITE; address=8'h1c; expected=32'h00000000; mask=32'hffffffff; end
            8'd4: begin operation=OP_WRITE; address=8'h20; expected=32'h00000000; mask=32'hffffffff; end
            8'd5: begin operation=OP_WRITE; address=8'h24; expected=32'h00000000; mask=32'hffffffff; end
            8'd6: begin operation=OP_WRITE; address=8'h28; expected=32'h00000000; mask=32'hffffffff; end
            8'd7: begin operation=OP_WRITE; address=8'h2c; expected=32'h00000001; mask=32'hffffffff; end
            8'd8: begin operation=OP_WRITE; address=8'h00; expected=32'h00000001; mask=32'hffffffff; end
            8'd9: begin operation=OP_WAIT; address=8'h04; expected=32'h00000000; mask=32'h00000000; end
            8'd10: begin operation=OP_CHECK; address=8'h04; expected=32'h00000015; mask=32'h0000001f; end
            8'd11: begin operation=OP_CHECK; address=8'h50; expected=32'h6b17d1f2; mask=32'hffffffff; end
            8'd12: begin operation=OP_CHECK; address=8'h54; expected=32'he12c4247; mask=32'hffffffff; end
            8'd13: begin operation=OP_CHECK; address=8'h58; expected=32'hf8bce6e5; mask=32'hffffffff; end
            8'd14: begin operation=OP_CHECK; address=8'h5c; expected=32'h63a440f2; mask=32'hffffffff; end
            8'd15: begin operation=OP_CHECK; address=8'h60; expected=32'h77037d81; mask=32'hffffffff; end
            8'd16: begin operation=OP_CHECK; address=8'h64; expected=32'h2deb33a0; mask=32'hffffffff; end
            8'd17: begin operation=OP_CHECK; address=8'h68; expected=32'hf4a13945; mask=32'hffffffff; end
            8'd18: begin operation=OP_CHECK; address=8'h6c; expected=32'hd898c296; mask=32'hffffffff; end
            8'd19: begin operation=OP_CHECK; address=8'h70; expected=32'h4fe342e2; mask=32'hffffffff; end
            8'd20: begin operation=OP_CHECK; address=8'h74; expected=32'hfe1a7f9b; mask=32'hffffffff; end
            8'd21: begin operation=OP_CHECK; address=8'h78; expected=32'h8ee7eb4a; mask=32'hffffffff; end
            8'd22: begin operation=OP_CHECK; address=8'h7c; expected=32'h7c0f9e16; mask=32'hffffffff; end
            8'd23: begin operation=OP_CHECK; address=8'h80; expected=32'h2bce3357; mask=32'hffffffff; end
            8'd24: begin operation=OP_CHECK; address=8'h84; expected=32'h6b315ece; mask=32'hffffffff; end
            8'd25: begin operation=OP_CHECK; address=8'h88; expected=32'hcbb64068; mask=32'hffffffff; end
            8'd26: begin operation=OP_CHECK; address=8'h8c; expected=32'h37bf51f5; mask=32'hffffffff; end
            8'd27: begin operation=OP_WRITE; address=8'h00; expected=32'h00000002; mask=32'hffffffff; end
            8'd28: begin operation=OP_WAIT; address=8'h04; expected=32'h00000000; mask=32'h00000000; end
            8'd29: begin operation=OP_CHECK; address=8'h04; expected=32'h00000035; mask=32'h0000003f; end
            8'd30: begin operation=OP_WRITE; address=8'h30; expected=32'haf2bdbe1; mask=32'hffffffff; end
            8'd31: begin operation=OP_WRITE; address=8'h34; expected=32'haa9b6ec1; mask=32'hffffffff; end
            8'd32: begin operation=OP_WRITE; address=8'h38; expected=32'he2ade1d6; mask=32'hffffffff; end
            8'd33: begin operation=OP_WRITE; address=8'h3c; expected=32'h94f41fc7; mask=32'hffffffff; end
            8'd34: begin operation=OP_WRITE; address=8'h40; expected=32'h1a831d02; mask=32'hffffffff; end
            8'd35: begin operation=OP_WRITE; address=8'h44; expected=32'h68e98915; mask=32'hffffffff; end
            8'd36: begin operation=OP_WRITE; address=8'h48; expected=32'h62113d8a; mask=32'hffffffff; end
            8'd37: begin operation=OP_WRITE; address=8'h4c; expected=32'h62add1bf; mask=32'hffffffff; end
            8'd38: begin operation=OP_CHECK; address=8'h10; expected=32'h00000000; mask=32'hffffffff; end
            8'd39: begin operation=OP_CHECK; address=8'h14; expected=32'h00000000; mask=32'hffffffff; end
            8'd40: begin operation=OP_CHECK; address=8'h18; expected=32'h00000000; mask=32'hffffffff; end
            8'd41: begin operation=OP_CHECK; address=8'h1c; expected=32'h00000000; mask=32'hffffffff; end
            8'd42: begin operation=OP_CHECK; address=8'h20; expected=32'h00000000; mask=32'hffffffff; end
            8'd43: begin operation=OP_CHECK; address=8'h24; expected=32'h00000000; mask=32'hffffffff; end
            8'd44: begin operation=OP_CHECK; address=8'h28; expected=32'h00000000; mask=32'hffffffff; end
            8'd45: begin operation=OP_CHECK; address=8'h2c; expected=32'h00000000; mask=32'hffffffff; end
            8'd46: begin operation=OP_WRITE; address=8'h2c; expected=32'h00000002; mask=32'hffffffff; end
            8'd47: begin operation=OP_CHECK; address=8'h04; expected=32'h00000039; mask=32'h0000003f; end
            8'd48: begin operation=OP_WRITE; address=8'h00; expected=32'h00000006; mask=32'hffffffff; end
            8'd49: begin operation=OP_WRITE; address=8'h00; expected=32'h00000004; mask=32'hffffffff; end
            8'd50: begin operation=OP_WAIT; address=8'h04; expected=32'h00000000; mask=32'h00000000; end
            8'd51: begin operation=OP_CHECK; address=8'h04; expected=32'h00000075; mask=32'h0000007f; end
            8'd52: begin operation=OP_CHECK; address=8'h90; expected=32'h04663411; mask=32'hffffffff; end
            8'd53: begin operation=OP_CHECK; address=8'h94; expected=32'h74d59e93; mask=32'hffffffff; end
            8'd54: begin operation=OP_CHECK; address=8'h98; expected=32'heb984c2a; mask=32'hffffffff; end
            8'd55: begin operation=OP_CHECK; address=8'h9c; expected=32'h7c923a80; mask=32'hffffffff; end
            8'd56: begin operation=OP_CHECK; address=8'ha0; expected=32'hab99a9e9; mask=32'hffffffff; end
            8'd57: begin operation=OP_CHECK; address=8'ha4; expected=32'h1555bc73; mask=32'hffffffff; end
            8'd58: begin operation=OP_CHECK; address=8'ha8; expected=32'hebd8073d; mask=32'hffffffff; end
            8'd59: begin operation=OP_CHECK; address=8'hac; expected=32'h4c722121; mask=32'hffffffff; end
            8'd60: begin operation=OP_CHECK; address=8'hb0; expected=32'h998f2b7b; mask=32'hffffffff; end
            8'd61: begin operation=OP_CHECK; address=8'hb4; expected=32'hb63082e9; mask=32'hffffffff; end
            8'd62: begin operation=OP_CHECK; address=8'hb8; expected=32'h76215e6a; mask=32'hffffffff; end
            8'd63: begin operation=OP_CHECK; address=8'hbc; expected=32'he46344d6; mask=32'hffffffff; end
            8'd64: begin operation=OP_CHECK; address=8'hc0; expected=32'h6d2d4ede; mask=32'hffffffff; end
            8'd65: begin operation=OP_CHECK; address=8'hc4; expected=32'ha67d65d9; mask=32'hffffffff; end
            8'd66: begin operation=OP_CHECK; address=8'hc8; expected=32'h1595f213; mask=32'hffffffff; end
            8'd67: begin operation=OP_CHECK; address=8'hcc; expected=32'h11df5030; mask=32'hffffffff; end
            8'd68: begin operation=OP_WRITE; address=8'h00; expected=32'h00000004; mask=32'hffffffff; end
            8'd69: begin operation=OP_DELAY; address=8'h04; expected=32'h00000800; mask=32'h00000000; end
            8'd70: begin operation=OP_CHECK; address=8'h04; expected=32'h00000002; mask=32'h00000002; end
            8'd71: begin operation=OP_WRITE; address=8'h00; expected=32'h00000005; mask=32'hffffffff; end
            8'd72: begin operation=OP_WAIT; address=8'h04; expected=32'h00000000; mask=32'h00000000; end
            8'd73: begin operation=OP_CHECK; address=8'h04; expected=32'h00000085; mask=32'h000000ff; end
            8'd74: begin operation=OP_CHECK; address=8'h50; expected=32'h00000000; mask=32'hffffffff; end
            8'd75: begin operation=OP_CHECK; address=8'h54; expected=32'h00000000; mask=32'hffffffff; end
            8'd76: begin operation=OP_CHECK; address=8'h58; expected=32'h00000000; mask=32'hffffffff; end
            8'd77: begin operation=OP_CHECK; address=8'h5c; expected=32'h00000000; mask=32'hffffffff; end
            8'd78: begin operation=OP_CHECK; address=8'h60; expected=32'h00000000; mask=32'hffffffff; end
            8'd79: begin operation=OP_CHECK; address=8'h64; expected=32'h00000000; mask=32'hffffffff; end
            8'd80: begin operation=OP_CHECK; address=8'h68; expected=32'h00000000; mask=32'hffffffff; end
            8'd81: begin operation=OP_CHECK; address=8'h6c; expected=32'h00000000; mask=32'hffffffff; end
            8'd82: begin operation=OP_CHECK; address=8'h70; expected=32'h00000000; mask=32'hffffffff; end
            8'd83: begin operation=OP_CHECK; address=8'h74; expected=32'h00000000; mask=32'hffffffff; end
            8'd84: begin operation=OP_CHECK; address=8'h78; expected=32'h00000000; mask=32'hffffffff; end
            8'd85: begin operation=OP_CHECK; address=8'h7c; expected=32'h00000000; mask=32'hffffffff; end
            8'd86: begin operation=OP_CHECK; address=8'h80; expected=32'h00000000; mask=32'hffffffff; end
            8'd87: begin operation=OP_CHECK; address=8'h84; expected=32'h00000000; mask=32'hffffffff; end
            8'd88: begin operation=OP_CHECK; address=8'h88; expected=32'h00000000; mask=32'hffffffff; end
            8'd89: begin operation=OP_CHECK; address=8'h8c; expected=32'h00000000; mask=32'hffffffff; end
            8'd90: begin operation=OP_CHECK; address=8'h90; expected=32'h00000000; mask=32'hffffffff; end
            8'd91: begin operation=OP_CHECK; address=8'h94; expected=32'h00000000; mask=32'hffffffff; end
            8'd92: begin operation=OP_CHECK; address=8'h98; expected=32'h00000000; mask=32'hffffffff; end
            8'd93: begin operation=OP_CHECK; address=8'h9c; expected=32'h00000000; mask=32'hffffffff; end
            8'd94: begin operation=OP_CHECK; address=8'ha0; expected=32'h00000000; mask=32'hffffffff; end
            8'd95: begin operation=OP_CHECK; address=8'ha4; expected=32'h00000000; mask=32'hffffffff; end
            8'd96: begin operation=OP_CHECK; address=8'ha8; expected=32'h00000000; mask=32'hffffffff; end
            8'd97: begin operation=OP_CHECK; address=8'hac; expected=32'h00000000; mask=32'hffffffff; end
            8'd98: begin operation=OP_CHECK; address=8'hb0; expected=32'h00000000; mask=32'hffffffff; end
            8'd99: begin operation=OP_CHECK; address=8'hb4; expected=32'h00000000; mask=32'hffffffff; end
            8'd100: begin operation=OP_CHECK; address=8'hb8; expected=32'h00000000; mask=32'hffffffff; end
            8'd101: begin operation=OP_CHECK; address=8'hbc; expected=32'h00000000; mask=32'hffffffff; end
            8'd102: begin operation=OP_CHECK; address=8'hc0; expected=32'h00000000; mask=32'hffffffff; end
            8'd103: begin operation=OP_CHECK; address=8'hc4; expected=32'h00000000; mask=32'hffffffff; end
            8'd104: begin operation=OP_CHECK; address=8'hc8; expected=32'h00000000; mask=32'hffffffff; end
            8'd105: begin operation=OP_CHECK; address=8'hcc; expected=32'h00000000; mask=32'hffffffff; end
            8'd106: begin operation=OP_CHECK; address=8'h10; expected=32'h00000000; mask=32'hffffffff; end
            8'd107: begin operation=OP_CHECK; address=8'h14; expected=32'h00000000; mask=32'hffffffff; end
            8'd108: begin operation=OP_CHECK; address=8'h18; expected=32'h00000000; mask=32'hffffffff; end
            8'd109: begin operation=OP_CHECK; address=8'h1c; expected=32'h00000000; mask=32'hffffffff; end
            8'd110: begin operation=OP_CHECK; address=8'h20; expected=32'h00000000; mask=32'hffffffff; end
            8'd111: begin operation=OP_CHECK; address=8'h24; expected=32'h00000000; mask=32'hffffffff; end
            8'd112: begin operation=OP_CHECK; address=8'h28; expected=32'h00000000; mask=32'hffffffff; end
            8'd113: begin operation=OP_CHECK; address=8'h2c; expected=32'h00000000; mask=32'hffffffff; end
            8'd114: begin operation=OP_END; address=8'h00; expected=32'h00000000; mask=32'h00000000; end
            default: operation=OP_END;
        endcase
    end
    always @(posedge clk or negedge rst_n) begin
        if(!rst_n) begin
            state<=ST_FETCH; pc<=0; wait_cycles<=0;
            bus_write<=0; bus_address<=0; bus_write_data<=0;
            finished<=0; passed<=0; failure_code<=0;
            provision_cycles<=0; sign_cycles<=0; operation_cycles<=0;
            timing_kind<=0; captured_sign<=0;
        end else begin
            bus_write<=0;
            // Count core BUSY clocks, excluding UART and host/test-controller overhead.
            if(bus_write && bus_address==0 && bus_write_data==1) begin
                timing_kind<=1; operation_cycles<=0;
            end else if(bus_write && bus_address==0 && bus_write_data==4 && !captured_sign) begin
                timing_kind<=2; operation_cycles<=0;
            end else if(timing_kind!=0) begin
                if(core_busy) operation_cycles<=operation_cycles+1'b1;
                else begin
                    if(timing_kind==1) provision_cycles<=operation_cycles;
                    else begin sign_cycles<=operation_cycles; captured_sign<=1; end
                    timing_kind<=0;
                end
            end
            if(!finished) case(state)
                ST_FETCH: begin
                    bus_address<=address; bus_write_data<=expected;
                    wait_cycles<=0; state<=ST_EXECUTE;
                end
                ST_EXECUTE: begin
                    case(operation)
                        OP_WRITE: begin bus_write<=1; state<=ST_SETTLE; end
                        OP_CHECK: begin
                            if((bus_read_data & mask)!=expected) begin
                                finished<=1; passed<=0; failure_code<=pc+1'b1;
                            end else begin pc<=pc+1'b1; state<=ST_FETCH; end
                        end
                        OP_WAIT: begin
                            if(!core_busy) begin pc<=pc+1'b1; state<=ST_FETCH; end
                            else if(wait_cycles>=WATCHDOG_CYCLES-1) begin
                                finished<=1; passed<=0; failure_code<=8'hff;
                            end else wait_cycles<=wait_cycles+1'b1;
                        end
                        OP_DELAY: begin
                            if(wait_cycles>=expected-1) begin pc<=pc+1'b1; state<=ST_FETCH; end
                            else wait_cycles<=wait_cycles+1'b1;
                        end
                        OP_END: begin finished<=1; passed<=1; end
                        default: begin finished<=1; passed<=0; failure_code<=8'hfe; end
                    endcase
                end
                ST_SETTLE: begin pc<=pc+1'b1; state<=ST_FETCH; end
                default: begin finished<=1; passed<=0; failure_code<=8'hfe; end
            endcase
        end
    end
endmodule
`default_nettype wire
